2014-04-08 00:31:37 [18716] [INFO] Starting gunicorn 18.0
2014-04-08 00:31:37 [18716] [DEBUG] Arbiter booted
2014-04-08 00:31:37 [18716] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (18716)
2014-04-08 00:31:37 [18716] [INFO] Using worker: sync
2014-04-08 00:31:37 [18721] [INFO] Booting worker with pid: 18721
2014-04-08 00:31:37 [18722] [INFO] Booting worker with pid: 18722
2014-04-08 00:31:38 [18723] [INFO] Booting worker with pid: 18723
2014-04-08 00:35:06 [18723] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 04:36:38 [18723] [DEBUG] GET /
2014-04-08 00:36:40 [18722] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 04:44:16 [18722] [DEBUG] GET /
2014-04-08 12:15:28 [18723] [DEBUG] GET /
2014-04-08 09:47:27 [18721] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 13:47:27 [18722] [DEBUG] GET /favicon.ico
2014-04-08 13:47:27 [18723] [DEBUG] GET /favicon.ico
2014-04-08 13:59:28 [18721] [DEBUG] GET /
2014-04-08 17:14:47 [18723] [DEBUG] GET /
2014-04-08 17:14:48 [18722] [DEBUG] GET /favicon.ico
2014-04-08 17:14:48 [18721] [DEBUG] GET /favicon.ico
2014-04-08 17:45:22 [18721] [DEBUG] GET /admin/assets.txt
2014-04-08 18:07:08 [18722] [DEBUG] GET /
2014-04-08 18:07:08 [18723] [DEBUG] GET /favicon.ico
2014-04-08 18:07:08 [18721] [DEBUG] GET /favicon.ico
2014-04-08 18:07:20 [18722] [DEBUG] GET /
2014-04-08 14:59:42 [21894] [INFO] Starting gunicorn 18.0
2014-04-08 14:59:42 [21894] [DEBUG] Arbiter booted
2014-04-08 14:59:42 [21894] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (21894)
2014-04-08 14:59:42 [21894] [INFO] Using worker: sync
2014-04-08 14:59:42 [21899] [INFO] Booting worker with pid: 21899
2014-04-08 14:59:42 [21900] [INFO] Booting worker with pid: 21900
2014-04-08 14:59:42 [21901] [INFO] Booting worker with pid: 21901
2014-04-08 14:59:46 [21901] [DEBUG] GET /admin/asfsd
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /admin/asfsd
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/TFGOL/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/auth/admin.py", line 182, in <module>
    admin.site.register(Group, GroupAdmin)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 105, in validate
    validator = cls.validator_class()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/validation.py", line 20, in __init__
    models.get_apps()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/loading.py", line 139, in get_apps
    self._populate()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/models.py", line 5, in <module>
    class ZipCode(models.Model):
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/models.py", line 10, in ZipCode
    zip = models.IntegerFIeld(primary_key=True)
AttributeError: 'module' object has no attribute 'IntegerFIeld'
2014-04-08 14:59:53 [21900] [DEBUG] GET /admin/
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/TFGOL/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/auth/admin.py", line 182, in <module>
    admin.site.register(Group, GroupAdmin)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 105, in validate
    validator = cls.validator_class()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/validation.py", line 20, in __init__
    models.get_apps()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/loading.py", line 139, in get_apps
    self._populate()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/models.py", line 5, in <module>
    class ZipCode(models.Model):
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/models.py", line 10, in ZipCode
    zip = models.IntegerFIeld(primary_key=True)
AttributeError: 'module' object has no attribute 'IntegerFIeld'
2014-04-08 15:01:00 [21894] [INFO] Handling signal: term
2014-04-08 15:01:00 [21899] [INFO] Worker exiting (pid: 21899)
2014-04-08 19:01:00 [21900] [INFO] Worker exiting (pid: 21900)
2014-04-08 19:01:00 [21901] [INFO] Worker exiting (pid: 21901)
2014-04-08 15:01:00 [21894] [INFO] Shutting down: Master
2014-04-08 15:01:00 [21920] [INFO] Starting gunicorn 18.0
2014-04-08 15:01:00 [21920] [DEBUG] Arbiter booted
2014-04-08 15:01:00 [21920] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (21920)
2014-04-08 15:01:00 [21920] [INFO] Using worker: sync
2014-04-08 15:01:00 [21925] [INFO] Booting worker with pid: 21925
2014-04-08 15:01:00 [21926] [INFO] Booting worker with pid: 21926
2014-04-08 15:01:00 [21927] [INFO] Booting worker with pid: 21927
2014-04-08 15:01:02 [21927] [DEBUG] GET /admin/
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 15:01:02 [21926] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:01:02 [21927] [DEBUG] GET /static/admin/css/login.css
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 19:01:05 [21927] [DEBUG] POST /admin/
2014-04-08 19:01:05 [21926] [DEBUG] GET /static/admin/css/base.css
2014-04-08 15:01:05 [21925] [DEBUG] GET /static/admin/css/login.css
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 19:01:08 [21926] [DEBUG] POST /admin/
2014-04-08 19:01:08 [21925] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:01:08 [21926] [DEBUG] GET /static/admin/css/login.css
2014-04-08 19:01:18 [21925] [DEBUG] POST /admin/
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 215, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 197, in inner
    return self.login(request)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 330, in login
    return login(request, **defaults)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/debug.py", line 75, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/auth/views.py", line 36, in login
    if form.is_valid():
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/forms.py", line 28, in clean
    self.user_cache = authenticate(username=username, password=password)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/auth/backends.py", line 16, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/auth/models.py", line 167, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/__init__.py", line 157, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/__init__.py", line 129, in _cursor
    self.ensure_connection()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/__init__.py", line 112, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/mysql/base.py", line 435, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")
2014-04-08 19:07:24 [21927] [DEBUG] POST /admin/
2014-04-08 19:07:24 [21926] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:07:24 [21927] [DEBUG] GET /static/admin/css/login.css
2014-04-08 19:08:20 [21927] [DEBUG] HEAD /
2014-04-08 19:08:20 [21927] [DEBUG] Ignoring EPIPE
2014-04-08 19:08:52 [21926] [DEBUG] POST /admin/
2014-04-08 19:08:52 [21927] [DEBUG] GET /admin/
2014-04-08 19:08:52 [21926] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:08:52 [21927] [DEBUG] GET /static/admin/css/dashboard.css
2014-04-08 19:09:05 [21927] [DEBUG] GET /admin/
2014-04-08 19:09:05 [21925] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:09:05 [21926] [DEBUG] GET /static/admin/css/dashboard.css
2014-04-08 19:09:08 [21927] [DEBUG] GET /admin/auth/group/
2014-04-08 19:09:08 [21925] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:09:08 [21926] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 19:09:08 [21927] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:09:08 [21926] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:09:08 [21925] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:09:08 [21927] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:09:08 [21925] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:09:08 [21927] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:09:09 [21925] [DEBUG] GET /static/admin/img/icon_searchbox.png
2014-04-08 19:09:09 [21926] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:09:09 [21925] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:09:09 [21926] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:09:09 [21925] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:09:09 [21926] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:09:09 [21925] [DEBUG] GET /static/admin/img/icon_searchbox.png
2014-04-08 19:13:15 [21925] [DEBUG] GET /admin/
2014-04-08 19:13:15 [21926] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:13:15 [21925] [DEBUG] GET /static/admin/css/dashboard.css
2014-04-08 15:13:25 [21920] [INFO] Handling signal: term
2014-04-08 19:13:25 [21925] [INFO] Worker exiting (pid: 21925)
2014-04-08 19:13:25 [21926] [INFO] Worker exiting (pid: 21926)
2014-04-08 19:13:25 [21927] [INFO] Worker exiting (pid: 21927)
2014-04-08 15:13:25 [21920] [INFO] Shutting down: Master
2014-04-08 15:13:39 [22184] [INFO] Starting gunicorn 18.0
2014-04-08 15:13:39 [22184] [DEBUG] Arbiter booted
2014-04-08 15:13:39 [22184] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22184)
2014-04-08 15:13:39 [22184] [INFO] Using worker: sync
2014-04-08 15:13:39 [22189] [INFO] Booting worker with pid: 22189
2014-04-08 15:13:39 [22190] [INFO] Booting worker with pid: 22190
2014-04-08 15:13:39 [22191] [INFO] Booting worker with pid: 22191
2014-04-08 15:13:40 [22190] [DEBUG] GET /admin/
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/TFGOL/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/admin.py", line 8, in <module>
    admin.site.register(WorkdsIn)
NameError: name 'WorkdsIn' is not defined
2014-04-08 15:13:59 [22184] [INFO] Handling signal: term
2014-04-08 15:13:59 [22189] [INFO] Worker exiting (pid: 22189)
2014-04-08 19:13:59 [22190] [INFO] Worker exiting (pid: 22190)
2014-04-08 15:13:59 [22191] [INFO] Worker exiting (pid: 22191)
2014-04-08 15:13:59 [22184] [INFO] Shutting down: Master
2014-04-08 15:13:59 [22203] [INFO] Starting gunicorn 18.0
2014-04-08 15:13:59 [22203] [DEBUG] Arbiter booted
2014-04-08 15:13:59 [22203] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22203)
2014-04-08 15:13:59 [22203] [INFO] Using worker: sync
2014-04-08 15:13:59 [22208] [INFO] Booting worker with pid: 22208
2014-04-08 15:13:59 [22209] [INFO] Booting worker with pid: 22209
2014-04-08 15:13:59 [22210] [INFO] Booting worker with pid: 22210
2014-04-08 15:14:05 [22209] [DEBUG] GET /admin/
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 15:14:06 [22208] [DEBUG] GET /static/admin/css/dashboard.css
2014-04-08 15:14:06 [22210] [DEBUG] GET /static/admin/css/base.css
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 19:14:10 [22209] [DEBUG] GET /admin/tfgol_web/zipcode/add/
2014-04-08 19:14:10 [22208] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:14:10 [22210] [DEBUG] GET /static/admin/css/forms.css
2014-04-08 19:14:11 [22209] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:14:11 [22210] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:14:11 [22208] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:14:11 [22210] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:14:11 [22208] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:14:11 [22209] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:14:11 [22208] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:14:11 [22209] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:14:11 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:14:11 [22209] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:14:11 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:14:47 [22208] [DEBUG] POST /admin/tfgol_web/zipcode/add/
2014-04-08 19:14:47 [22209] [DEBUG] GET /admin/tfgol_web/zipcode/
2014-04-08 19:14:47 [22208] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:14:47 [22210] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:14:47 [22209] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 19:14:47 [22210] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:14:47 [22209] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:14:47 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:14:47 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:14:47 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:14:47 [22210] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:14:48 [22208] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:14:48 [22210] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:14:48 [22208] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:14:48 [22210] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:14:54 [22208] [DEBUG] GET /admin/tfgol_web/
2014-04-08 19:14:54 [22210] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:14:54 [22209] [DEBUG] GET /static/admin/css/dashboard.css
2014-04-08 19:15:56 [22210] [DEBUG] GET /admin/tfgol_web/job/
2014-04-08 19:15:56 [22209] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:15:57 [22210] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 19:15:57 [22209] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:15:57 [22210] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:15:57 [22208] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:15:57 [22209] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:15:57 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:15:57 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:15:57 [22209] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:15:57 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:15:57 [22209] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:15:58 [22210] [DEBUG] GET /admin/tfgol_web/job/add/
2014-04-08 19:15:58 [22209] [DEBUG] GET /static/admin/css/forms.css
2014-04-08 19:15:58 [22208] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:15:58 [22210] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:15:58 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:15:58 [22209] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:15:58 [22208] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:15:58 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:15:58 [22209] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:15:58 [22208] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:15:59 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:15:59 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:15:59 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:15:59 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:17 [22210] [DEBUG] POST /admin/tfgol_web/job/add/
2014-04-08 19:16:17 [22208] [DEBUG] GET /admin/tfgol_web/job/
2014-04-08 19:16:17 [22210] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 19:16:17 [22209] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:16:17 [22208] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:16:17 [22209] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:17 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:17 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:17 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:17 [22209] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:17 [22208] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:17 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:17 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:17 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:17 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:21 [22208] [DEBUG] GET /admin/tfgol_web/
2014-04-08 19:16:22 [22210] [DEBUG] GET /static/admin/css/dashboard.css
2014-04-08 19:16:22 [22209] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:16:23 [22208] [DEBUG] GET /admin/tfgol_web/worksin/
2014-04-08 19:16:23 [22209] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:16:23 [22210] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:16:23 [22208] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 19:16:23 [22209] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:23 [22208] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:23 [22210] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:23 [22209] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:23 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:23 [22210] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:24 [22208] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:24 [22210] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:25 [22208] [DEBUG] GET /admin/tfgol_web/worksin/add/
2014-04-08 19:16:25 [22210] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:16:25 [22208] [DEBUG] GET /static/admin/css/forms.css
2014-04-08 19:16:25 [22209] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:16:25 [22210] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:25 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:25 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:25 [22209] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:25 [22210] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:26 [22209] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:26 [22208] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:16:26 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:26 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:26 [22210] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:26 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:26 [22210] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:16:36 [22210] [DEBUG] POST /admin/tfgol_web/worksin/add/
2014-04-08 19:16:36 [22208] [DEBUG] GET /static/admin/css/forms.css
2014-04-08 19:16:36 [22209] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:16:36 [22210] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:16:36 [22209] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:36 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:36 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:36 [22208] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:36 [22209] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:37 [22210] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:37 [22208] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:16:37 [22209] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:37 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:37 [22209] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:37 [22208] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:37 [22209] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:16:51 [22208] [DEBUG] POST /admin/tfgol_web/worksin/add/
2014-04-08 19:16:51 [22209] [DEBUG] GET /static/admin/css/forms.css
2014-04-08 19:16:51 [22210] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:16:51 [22208] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:51 [22210] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:51 [22209] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:16:51 [22208] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:51 [22210] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:51 [22208] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:51 [22209] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:16:51 [22210] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:16:51 [22208] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:16:51 [22209] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:16:51 [22208] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:16:52 [22209] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:16:52 [22208] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 15:17:36 [22203] [INFO] Handling signal: term
2014-04-08 19:17:36 [22208] [INFO] Worker exiting (pid: 22208)
2014-04-08 19:17:36 [22209] [INFO] Worker exiting (pid: 22209)
2014-04-08 19:17:36 [22210] [INFO] Worker exiting (pid: 22210)
2014-04-08 15:17:36 [22203] [INFO] Shutting down: Master
2014-04-08 15:17:47 [22278] [INFO] Starting gunicorn 18.0
2014-04-08 15:17:47 [22278] [DEBUG] Arbiter booted
2014-04-08 15:17:47 [22278] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22278)
2014-04-08 15:17:47 [22278] [INFO] Using worker: sync
2014-04-08 15:17:47 [22283] [INFO] Booting worker with pid: 22283
2014-04-08 15:17:47 [22284] [INFO] Booting worker with pid: 22284
2014-04-08 15:17:47 [22285] [INFO] Booting worker with pid: 22285
2014-04-08 15:17:51 [22284] [DEBUG] POST /admin/tfgol_web/worksin/add/
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /admin/tfgol_web/worksin/add/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 1131, in add_view
    self.save_model(request, new_object, form, False)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 860, in save_model
    obj.save()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Out of range value for column 'percent' at row 1
2014-04-08 15:19:47 [22278] [INFO] Handling signal: term
2014-04-08 15:19:47 [22283] [INFO] Worker exiting (pid: 22283)
2014-04-08 19:19:47 [22284] [INFO] Worker exiting (pid: 22284)
2014-04-08 15:19:47 [22285] [INFO] Worker exiting (pid: 22285)
2014-04-08 15:19:47 [22278] [INFO] Shutting down: Master
2014-04-08 15:19:56 [22302] [INFO] Starting gunicorn 18.0
2014-04-08 15:19:56 [22302] [DEBUG] Arbiter booted
2014-04-08 15:19:56 [22302] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22302)
2014-04-08 15:19:56 [22302] [INFO] Using worker: sync
2014-04-08 15:19:56 [22307] [INFO] Booting worker with pid: 22307
2014-04-08 15:19:56 [22308] [INFO] Booting worker with pid: 22308
2014-04-08 15:19:56 [22309] [INFO] Booting worker with pid: 22309
2014-04-08 15:19:57 [22307] [DEBUG] POST /admin/tfgol_web/worksin/add/
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /admin/tfgol_web/worksin/add/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 1131, in add_view
    self.save_model(request, new_object, form, False)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 860, in save_model
    obj.save()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Out of range value for column 'percent' at row 1
2014-04-08 19:20:08 [22307] [DEBUG] GET /admin/tfgol_web/worksin/
2014-04-08 15:20:09 [22309] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:20:09 [22307] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 15:20:09 [22308] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:20:09 [22307] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:20:09 [22307] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:20:09 [22307] [DEBUG] GET /static/admin/js/jquery.js
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 19:20:09 [22307] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:20:09 [22307] [DEBUG] GET /static/admin/js/actions.js
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 19:20:09 [22309] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:20:09 [22308] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:20:09 [22309] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:20:09 [22308] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:20:10 [22309] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:20:17 [22309] [DEBUG] POST /admin/tfgol_web/worksin/
2014-04-08 19:20:18 [22308] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:20:22 [22309] [DEBUG] POST /admin/tfgol_web/worksin/
2014-04-08 19:20:22 [22308] [DEBUG] GET /admin/tfgol_web/worksin/
2014-04-08 19:20:22 [22309] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:20:22 [22307] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:20:22 [22308] [DEBUG] GET /static/admin/css/changelists.css
2014-04-08 19:20:22 [22309] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:20:22 [22307] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:20:22 [22308] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:20:22 [22308] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:20:22 [22309] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:20:22 [22308] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:20:22 [22309] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:20:23 [22308] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:20:23 [22309] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:20:23 [22308] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:20:26 [22309] [DEBUG] GET /admin/tfgol_web/worksin/add/
2014-04-08 19:20:26 [22308] [DEBUG] GET /static/admin/css/base.css
2014-04-08 19:20:26 [22307] [DEBUG] GET /static/admin/css/forms.css
2014-04-08 19:20:26 [22309] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:20:26 [22307] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:20:26 [22308] [DEBUG] GET /admin/jsi18n/
2014-04-08 19:20:26 [22309] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:20:26 [22307] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:20:26 [22309] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:20:26 [22308] [DEBUG] GET /static/admin/js/core.js
2014-04-08 19:20:26 [22307] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:20:26 [22309] [DEBUG] GET /static/admin/js/admin/RelatedObjectLookups.js
2014-04-08 19:20:26 [22307] [DEBUG] GET /static/admin/js/jquery.js
2014-04-08 19:20:26 [22309] [DEBUG] GET /static/admin/js/jquery.init.js
2014-04-08 19:20:26 [22307] [DEBUG] GET /static/admin/js/actions.js
2014-04-08 19:20:26 [22309] [DEBUG] GET /static/admin/img/icon_addlink.gif
2014-04-08 19:20:32 [22307] [DEBUG] POST /admin/tfgol_web/worksin/add/
Internal Server Error: /admin/tfgol_web/worksin/add/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 432, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 1131, in add_view
    self.save_model(request, new_object, form, False)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/contrib/admin/options.py", line 860, in save_model
    obj.save()
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Out of range value for column 'percent' at row 1
2014-04-08 15:37:13 [22302] [INFO] Handling signal: term
2014-04-08 19:37:13 [22307] [INFO] Worker exiting (pid: 22307)
2014-04-08 19:37:13 [22308] [INFO] Worker exiting (pid: 22308)
2014-04-08 19:37:13 [22309] [INFO] Worker exiting (pid: 22309)
2014-04-08 15:37:13 [22302] [INFO] Shutting down: Master
2014-04-08 15:38:18 [22384] [INFO] Starting gunicorn 18.0
2014-04-08 15:38:18 [22384] [DEBUG] Arbiter booted
2014-04-08 15:38:18 [22384] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22384)
2014-04-08 15:38:18 [22384] [INFO] Using worker: sync
2014-04-08 15:38:18 [22389] [INFO] Booting worker with pid: 22389
2014-04-08 15:38:18 [22390] [INFO] Booting worker with pid: 22390
2014-04-08 15:38:18 [22391] [INFO] Booting worker with pid: 22391
2014-04-08 15:38:30 [22390] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 15:38:52 [22384] [INFO] Handling signal: term
2014-04-08 15:38:52 [22389] [INFO] Worker exiting (pid: 22389)
2014-04-08 19:38:52 [22390] [INFO] Worker exiting (pid: 22390)
2014-04-08 15:38:52 [22391] [INFO] Worker exiting (pid: 22391)
2014-04-08 15:38:52 [22384] [INFO] Shutting down: Master
2014-04-08 15:38:52 [22402] [INFO] Starting gunicorn 18.0
2014-04-08 15:38:52 [22402] [DEBUG] Arbiter booted
2014-04-08 15:38:52 [22402] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22402)
2014-04-08 15:38:52 [22402] [INFO] Using worker: sync
2014-04-08 15:38:52 [22407] [INFO] Booting worker with pid: 22407
2014-04-08 15:38:52 [22408] [INFO] Booting worker with pid: 22408
2014-04-08 15:38:53 [22409] [INFO] Booting worker with pid: 22409
2014-04-08 15:38:54 [22408] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 23, in mainpage
    zip = randomZip()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 11, in randomZip
    totalpop = ZipCode.objects.all().annotate(Sum('population_thousands'))
NameError: global name 'Sum' is not defined
2014-04-08 19:38:58 [22408] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 23, in mainpage
    zip = randomZip()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 11, in randomZip
    totalpop = ZipCode.objects.all().annotate(Sum('population_thousands'))
NameError: global name 'Sum' is not defined
2014-04-08 15:41:21 [22402] [INFO] Handling signal: term
2014-04-08 19:41:21 [22408] [INFO] Worker exiting (pid: 22408)
2014-04-08 15:41:21 [22409] [INFO] Worker exiting (pid: 22409)
2014-04-08 15:41:21 [22407] [INFO] Worker exiting (pid: 22407)
2014-04-08 15:41:21 [22402] [INFO] Shutting down: Master
2014-04-08 15:41:21 [22425] [INFO] Starting gunicorn 18.0
2014-04-08 15:41:21 [22425] [DEBUG] Arbiter booted
2014-04-08 15:41:21 [22425] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22425)
2014-04-08 15:41:21 [22425] [INFO] Using worker: sync
2014-04-08 15:41:21 [22430] [INFO] Booting worker with pid: 22430
2014-04-08 15:41:21 [22431] [INFO] Booting worker with pid: 22431
2014-04-08 15:41:21 [22432] [INFO] Booting worker with pid: 22432
2014-04-08 15:41:24 [22431] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 23, in mainpage
    zip = randomZip()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 11, in randomZip
    totalpop = ZipCode.objects.all().aggregate(Sum('population_thousands'))
NameError: global name 'Sum' is not defined
2014-04-08 15:42:10 [22425] [INFO] Handling signal: term
2014-04-08 15:42:10 [22432] [INFO] Worker exiting (pid: 22432)
2014-04-08 15:42:10 [22430] [INFO] Worker exiting (pid: 22430)
2014-04-08 19:42:10 [22431] [INFO] Worker exiting (pid: 22431)
2014-04-08 15:42:10 [22425] [INFO] Shutting down: Master
2014-04-08 15:42:11 [22442] [INFO] Starting gunicorn 18.0
2014-04-08 15:42:11 [22442] [DEBUG] Arbiter booted
2014-04-08 15:42:11 [22442] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22442)
2014-04-08 15:42:11 [22442] [INFO] Using worker: sync
2014-04-08 15:42:11 [22447] [INFO] Booting worker with pid: 22447
2014-04-08 15:42:11 [22448] [INFO] Booting worker with pid: 22448
2014-04-08 15:42:11 [22449] [INFO] Booting worker with pid: 22449
2014-04-08 15:42:13 [22448] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 24, in mainpage
    zip = randomZip()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 14, in randomZip
    rand = random.uniform(0,totalpop)
  File "/usr/lib64/python2.6/random.py", line 353, in uniform
    return a + (b-a) * self.random()
TypeError: unsupported operand type(s) for -: 'dict' and 'int'
2014-04-08 15:42:46 [22442] [INFO] Handling signal: term
2014-04-08 19:42:46 [22448] [INFO] Worker exiting (pid: 22448)
2014-04-08 15:42:46 [22449] [INFO] Worker exiting (pid: 22449)
2014-04-08 15:42:46 [22447] [INFO] Worker exiting (pid: 22447)
2014-04-08 15:42:46 [22442] [INFO] Shutting down: Master
2014-04-08 15:42:46 [22462] [INFO] Starting gunicorn 18.0
2014-04-08 15:42:46 [22462] [DEBUG] Arbiter booted
2014-04-08 15:42:46 [22462] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22462)
2014-04-08 15:42:46 [22462] [INFO] Using worker: sync
2014-04-08 15:42:46 [22467] [INFO] Booting worker with pid: 22467
2014-04-08 15:42:46 [22468] [INFO] Booting worker with pid: 22468
2014-04-08 15:42:46 [22469] [INFO] Booting worker with pid: 22469
2014-04-08 15:42:52 [22468] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 24, in mainpage
    zip = randomZip()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 12, in randomZip
    totalpop = ZipCode.objects.all().aggregate(Sum('population_thousands')).get()
TypeError: get expected at least 1 arguments, got 0
2014-04-08 15:44:28 [22462] [INFO] Handling signal: term
2014-04-08 15:44:28 [22467] [INFO] Worker exiting (pid: 22467)
2014-04-08 19:44:28 [22468] [INFO] Worker exiting (pid: 22468)
2014-04-08 15:44:28 [22469] [INFO] Worker exiting (pid: 22469)
2014-04-08 15:44:28 [22462] [INFO] Shutting down: Master
2014-04-08 15:44:28 [22482] [INFO] Starting gunicorn 18.0
2014-04-08 15:44:28 [22482] [DEBUG] Arbiter booted
2014-04-08 15:44:28 [22482] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22482)
2014-04-08 15:44:28 [22482] [INFO] Using worker: sync
2014-04-08 15:44:28 [22487] [INFO] Booting worker with pid: 22487
2014-04-08 15:44:28 [22488] [INFO] Booting worker with pid: 22488
2014-04-08 15:44:28 [22489] [INFO] Booting worker with pid: 22489
2014-04-08 15:44:32 [22488] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 24, in mainpage
    zip = randomZip()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 14, in randomZip
    rand = random.uniform(0,totalpop)
  File "/usr/lib64/python2.6/random.py", line 353, in uniform
    return a + (b-a) * self.random()
TypeError: unsupported operand type(s) for -: 'dict' and 'int'
2014-04-08 15:45:08 [22482] [INFO] Handling signal: term
2014-04-08 19:45:08 [22488] [INFO] Worker exiting (pid: 22488)
2014-04-08 15:45:08 [22489] [INFO] Worker exiting (pid: 22489)
2014-04-08 15:45:08 [22487] [INFO] Worker exiting (pid: 22487)
2014-04-08 15:45:08 [22482] [INFO] Shutting down: Master
2014-04-08 15:45:08 [22518] [INFO] Starting gunicorn 18.0
2014-04-08 15:45:08 [22518] [DEBUG] Arbiter booted
2014-04-08 15:45:08 [22518] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22518)
2014-04-08 15:45:08 [22518] [INFO] Using worker: sync
2014-04-08 15:45:08 [22523] [INFO] Booting worker with pid: 22523
2014-04-08 15:45:08 [22524] [INFO] Booting worker with pid: 22524
2014-04-08 15:45:08 [22525] [INFO] Booting worker with pid: 22525
2014-04-08 15:45:10 [22524] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 15:53:43 [22518] [INFO] Handling signal: term
2014-04-08 15:53:43 [22523] [INFO] Worker exiting (pid: 22523)
2014-04-08 19:53:43 [22524] [INFO] Worker exiting (pid: 22524)
2014-04-08 15:53:43 [22525] [INFO] Worker exiting (pid: 22525)
2014-04-08 15:53:43 [22518] [INFO] Shutting down: Master
2014-04-08 15:53:44 [22552] [INFO] Starting gunicorn 18.0
2014-04-08 15:53:44 [22552] [DEBUG] Arbiter booted
2014-04-08 15:53:44 [22552] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22552)
2014-04-08 15:53:44 [22552] [INFO] Using worker: sync
2014-04-08 15:53:44 [22557] [INFO] Booting worker with pid: 22557
2014-04-08 15:53:44 [22558] [INFO] Booting worker with pid: 22558
2014-04-08 15:53:44 [22559] [INFO] Booting worker with pid: 22559
2014-04-08 15:53:46 [22558] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 27, in mainpage
    p = Person(zip)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 26, in __init__
    self.current_zip_num = zip.zip
AttributeError: 'long' object has no attribute 'zip'
2014-04-08 16:16:31 [22559] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 27, in mainpage
    p = Person(zip)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 28, in __init__
    self.current_zip_num = zip.zip
AttributeError: 'long' object has no attribute 'zip'
2014-04-08 16:16:32 [22557] [DEBUG] GET /favicon.ico
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 27, in mainpage
    p = Person(zip)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 28, in __init__
    self.current_zip_num = zip.zip
AttributeError: 'long' object has no attribute 'zip'
2014-04-08 20:16:32 [22559] [DEBUG] GET /favicon.ico
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 27, in mainpage
    p = Person(zip)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 28, in __init__
    self.current_zip_num = zip.zip
AttributeError: 'long' object has no attribute 'zip'
2014-04-08 16:18:32 [22552] [INFO] Handling signal: term
2014-04-08 20:18:32 [22557] [INFO] Worker exiting (pid: 22557)
2014-04-08 20:18:32 [22558] [INFO] Worker exiting (pid: 22558)
2014-04-08 20:18:32 [22559] [INFO] Worker exiting (pid: 22559)
2014-04-08 16:18:32 [22552] [INFO] Shutting down: Master
2014-04-08 16:18:32 [22698] [INFO] Starting gunicorn 18.0
2014-04-08 16:18:32 [22698] [DEBUG] Arbiter booted
2014-04-08 16:18:32 [22698] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22698)
2014-04-08 16:18:32 [22698] [INFO] Using worker: sync
2014-04-08 16:18:32 [22703] [INFO] Booting worker with pid: 22703
2014-04-08 16:18:33 [22704] [INFO] Booting worker with pid: 22704
2014-04-08 16:18:33 [22705] [INFO] Booting worker with pid: 22705
2014-04-08 16:18:36 [22704] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 29, in mainpage
    p.step()
TypeError: step() takes no arguments (1 given)
2014-04-08 16:19:54 [22698] [INFO] Handling signal: term
2014-04-08 20:19:54 [22704] [INFO] Worker exiting (pid: 22704)
2014-04-08 16:19:54 [22705] [INFO] Worker exiting (pid: 22705)
2014-04-08 16:19:54 [22703] [INFO] Worker exiting (pid: 22703)
2014-04-08 16:19:54 [22698] [INFO] Shutting down: Master
2014-04-08 16:19:55 [22720] [INFO] Starting gunicorn 18.0
2014-04-08 16:19:55 [22720] [DEBUG] Arbiter booted
2014-04-08 16:19:55 [22720] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22720)
2014-04-08 16:19:55 [22720] [INFO] Using worker: sync
2014-04-08 16:19:55 [22725] [INFO] Booting worker with pid: 22725
2014-04-08 16:19:55 [22726] [INFO] Booting worker with pid: 22726
2014-04-08 16:19:55 [22727] [INFO] Booting worker with pid: 22727
2014-04-08 16:19:56 [22726] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 29, in mainpage
    p.step()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 41, in step
    ++age
NameError: global name 'age' is not defined
2014-04-08 16:20:07 [22720] [INFO] Handling signal: term
2014-04-08 16:20:07 [22725] [INFO] Worker exiting (pid: 22725)
2014-04-08 20:20:07 [22726] [INFO] Worker exiting (pid: 22726)
2014-04-08 16:20:07 [22727] [INFO] Worker exiting (pid: 22727)
2014-04-08 16:20:07 [22720] [INFO] Shutting down: Master
2014-04-08 16:20:07 [22743] [INFO] Starting gunicorn 18.0
2014-04-08 16:20:07 [22743] [DEBUG] Arbiter booted
2014-04-08 16:20:07 [22743] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22743)
2014-04-08 16:20:07 [22743] [INFO] Using worker: sync
2014-04-08 16:20:07 [22748] [INFO] Booting worker with pid: 22748
2014-04-08 16:20:07 [22749] [INFO] Booting worker with pid: 22749
2014-04-08 16:20:07 [22750] [INFO] Booting worker with pid: 22750
2014-04-08 16:20:42 [22743] [INFO] Handling signal: term
2014-04-08 16:20:42 [22748] [INFO] Worker exiting (pid: 22748)
2014-04-08 16:20:42 [22749] [INFO] Worker exiting (pid: 22749)
2014-04-08 16:20:42 [22750] [INFO] Worker exiting (pid: 22750)
2014-04-08 16:20:42 [22743] [INFO] Shutting down: Master
2014-04-08 16:20:42 [22761] [INFO] Starting gunicorn 18.0
2014-04-08 16:20:42 [22761] [DEBUG] Arbiter booted
2014-04-08 16:20:42 [22761] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22761)
2014-04-08 16:20:42 [22761] [INFO] Using worker: sync
2014-04-08 16:20:42 [22766] [INFO] Booting worker with pid: 22766
2014-04-08 16:20:42 [22767] [INFO] Booting worker with pid: 22767
2014-04-08 16:20:42 [22768] [INFO] Booting worker with pid: 22768
2014-04-08 16:20:44 [22767] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 16:22:47 [22761] [INFO] Handling signal: term
2014-04-08 16:22:47 [22766] [INFO] Worker exiting (pid: 22766)
2014-04-08 20:22:47 [22767] [INFO] Worker exiting (pid: 22767)
2014-04-08 16:22:47 [22768] [INFO] Worker exiting (pid: 22768)
2014-04-08 16:22:47 [22761] [INFO] Shutting down: Master
2014-04-08 16:22:47 [22784] [INFO] Starting gunicorn 18.0
2014-04-08 16:22:47 [22784] [DEBUG] Arbiter booted
2014-04-08 16:22:47 [22784] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (22784)
2014-04-08 16:22:47 [22784] [INFO] Using worker: sync
2014-04-08 16:22:47 [22789] [INFO] Booting worker with pid: 22789
2014-04-08 16:22:47 [22790] [INFO] Booting worker with pid: 22790
2014-04-08 16:22:47 [22791] [INFO] Booting worker with pid: 22791
2014-04-08 16:22:51 [22790] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 20:50:30 [22790] [DEBUG] GET /
2014-04-08 16:50:32 [22791] [DEBUG] GET /favicon.ico
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 18:17:20 [22789] [DEBUG] GET /wp-login.php
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-08 22:17:20 [22791] [DEBUG] GET /blog/wp-login.php
2014-04-08 22:17:21 [22789] [DEBUG] GET /wp/wp-login.php
2014-04-08 22:17:21 [22790] [DEBUG] GET /wordpress/wp-login.php
2014-04-08 22:17:22 [22789] [DEBUG] GET /journal/wp-login.php
2014-04-08 22:18:00 [22789] [DEBUG] HEAD /
2014-04-08 22:18:00 [22789] [DEBUG] Ignoring EPIPE
2014-04-08 23:07:01 [22790] [DEBUG] GET /wp-login.php
2014-04-08 23:07:01 [22791] [DEBUG] GET /blog/wp-login.php
2014-04-08 23:07:01 [22790] [DEBUG] GET /wp/wp-login.php
2014-04-08 23:07:02 [22791] [DEBUG] GET /wordpress/wp-login.php
2014-04-08 23:07:03 [22790] [DEBUG] GET /journal/wp-login.php
2014-04-09 04:09:42 [22790] [DEBUG] GET /
2014-04-09 04:09:42 [22789] [DEBUG] GET /favicon.ico
2014-04-09 04:09:42 [22790] [DEBUG] GET /favicon.ico
2014-04-09 04:20:48 [22790] [DEBUG] GET /w00tw00t.at.blackhats.romanian.anti-sec:)
2014-04-09 04:20:49 [22789] [DEBUG] GET /phpMyAdmin/scripts/setup.php
2014-04-09 04:20:49 [22790] [DEBUG] GET /phpmyadmin/scripts/setup.php
2014-04-09 04:20:49 [22789] [DEBUG] GET /pma/scripts/setup.php
2014-04-09 04:20:50 [22790] [DEBUG] GET /myadmin/scripts/setup.php
2014-04-09 04:20:50 [22789] [DEBUG] GET /MyAdmin/scripts/setup.php
2014-04-09 00:35:27 [22784] [INFO] Handling signal: term
2014-04-09 04:35:27 [22789] [INFO] Worker exiting (pid: 22789)
2014-04-09 04:35:27 [22790] [INFO] Worker exiting (pid: 22790)
2014-04-09 04:35:27 [22791] [INFO] Worker exiting (pid: 22791)
2014-04-09 00:35:28 [22784] [INFO] Shutting down: Master
2014-04-09 00:35:28 [24430] [INFO] Starting gunicorn 18.0
2014-04-09 00:35:28 [24430] [DEBUG] Arbiter booted
2014-04-09 00:35:28 [24430] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (24430)
2014-04-09 00:35:28 [24430] [INFO] Using worker: sync
2014-04-09 00:35:28 [24435] [INFO] Booting worker with pid: 24435
2014-04-09 00:35:28 [24436] [INFO] Booting worker with pid: 24436
2014-04-09 00:35:28 [24437] [INFO] Booting worker with pid: 24437
2014-04-09 00:35:37 [24437] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/TFGOL/urls.py", line 4, in <module>
    from tfgol_web import views
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 7, in <module>
    from tfgol_web.person import Person
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 3, in <module>
    import roll_age
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/roll_age.py", line 1, in <module>
    from person import Person
ImportError: cannot import name Person
2014-04-09 00:36:36 [24430] [INFO] Handling signal: term
2014-04-09 00:36:36 [24435] [INFO] Worker exiting (pid: 24435)
2014-04-09 00:36:36 [24436] [INFO] Worker exiting (pid: 24436)
2014-04-09 04:36:36 [24437] [INFO] Worker exiting (pid: 24437)
2014-04-09 00:36:36 [24430] [INFO] Shutting down: Master
2014-04-09 00:36:37 [24454] [INFO] Starting gunicorn 18.0
2014-04-09 00:36:37 [24454] [DEBUG] Arbiter booted
2014-04-09 00:36:37 [24454] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (24454)
2014-04-09 00:36:37 [24454] [INFO] Using worker: sync
2014-04-09 00:36:37 [24459] [INFO] Booting worker with pid: 24459
2014-04-09 00:36:37 [24460] [INFO] Booting worker with pid: 24460
2014-04-09 00:36:37 [24461] [INFO] Booting worker with pid: 24461
2014-04-09 00:36:38 [24460] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/TFGOL/urls.py", line 4, in <module>
    from tfgol_web import views
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 7, in <module>
    from tfgol_web.person import Person
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 4, in <module>
    import roll_death
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/roll_death.py", line 1, in <module>
    from person import Person
ImportError: cannot import name Person
2014-04-09 00:38:02 [24454] [INFO] Handling signal: term
2014-04-09 00:38:02 [24459] [INFO] Worker exiting (pid: 24459)
2014-04-09 04:38:02 [24460] [INFO] Worker exiting (pid: 24460)
2014-04-09 00:38:02 [24461] [INFO] Worker exiting (pid: 24461)
2014-04-09 00:38:02 [24454] [INFO] Shutting down: Master
2014-04-09 00:38:02 [24480] [INFO] Starting gunicorn 18.0
2014-04-09 00:38:02 [24480] [DEBUG] Arbiter booted
2014-04-09 00:38:02 [24480] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (24480)
2014-04-09 00:38:02 [24480] [INFO] Using worker: sync
2014-04-09 00:38:02 [24485] [INFO] Booting worker with pid: 24485
2014-04-09 00:38:02 [24486] [INFO] Booting worker with pid: 24486
2014-04-09 00:38:02 [24487] [INFO] Booting worker with pid: 24487
2014-04-09 00:38:03 [24486] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 29, in mainpage
    p.step()
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/person.py", line 52, in step
    self.age = roll_age(self)
TypeError: 'module' object is not callable
2014-04-09 00:42:59 [24480] [INFO] Handling signal: term
2014-04-09 00:42:59 [24485] [INFO] Worker exiting (pid: 24485)
2014-04-09 04:42:59 [24486] [INFO] Worker exiting (pid: 24486)
2014-04-09 00:42:59 [24487] [INFO] Worker exiting (pid: 24487)
2014-04-09 00:42:59 [24480] [INFO] Shutting down: Master
2014-04-09 00:42:59 [24528] [INFO] Starting gunicorn 18.0
2014-04-09 00:42:59 [24528] [DEBUG] Arbiter booted
2014-04-09 00:42:59 [24528] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (24528)
2014-04-09 00:42:59 [24528] [INFO] Using worker: sync
2014-04-09 00:42:59 [24533] [INFO] Booting worker with pid: 24533
2014-04-09 00:42:59 [24534] [INFO] Booting worker with pid: 24534
2014-04-09 00:42:59 [24535] [INFO] Booting worker with pid: 24535
2014-04-09 00:43:01 [24534] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.2-py2.6.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/eecs493/TheFatalisticGameOfLife/python/TFGOL/tfgol_web/views.py", line 32, in mainpage
    return render(request, 'index.html', { 'name': p.name, 'income':p.income, 'networth':p.networth, 'job':p.job })
AttributeError: Person instance has no attribute 'job'
2014-04-09 00:43:28 [24528] [INFO] Handling signal: term
2014-04-09 00:43:28 [24533] [INFO] Worker exiting (pid: 24533)
2014-04-09 04:43:28 [24534] [INFO] Worker exiting (pid: 24534)
2014-04-09 00:43:28 [24535] [INFO] Worker exiting (pid: 24535)
2014-04-09 00:43:28 [24528] [INFO] Shutting down: Master
2014-04-09 00:43:29 [24549] [INFO] Starting gunicorn 18.0
2014-04-09 00:43:29 [24549] [DEBUG] Arbiter booted
2014-04-09 00:43:29 [24549] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (24549)
2014-04-09 00:43:29 [24549] [INFO] Using worker: sync
2014-04-09 00:43:29 [24554] [INFO] Booting worker with pid: 24554
2014-04-09 00:43:29 [24555] [INFO] Booting worker with pid: 24555
2014-04-09 00:43:29 [24556] [INFO] Booting worker with pid: 24556
2014-04-09 00:43:30 [24555] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-09 00:43:41 [24556] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-09 04:43:42 [24555] [DEBUG] GET /
2014-04-09 04:43:43 [24556] [DEBUG] GET /
2014-04-09 04:43:43 [24555] [DEBUG] GET /
2014-04-09 04:43:44 [24556] [DEBUG] GET /
2014-04-09 04:43:44 [24555] [DEBUG] GET /
2014-04-09 00:46:34 [24549] [INFO] Handling signal: term
2014-04-09 00:46:34 [24554] [INFO] Worker exiting (pid: 24554)
2014-04-09 04:46:34 [24555] [INFO] Worker exiting (pid: 24555)
2014-04-09 04:46:34 [24556] [INFO] Worker exiting (pid: 24556)
2014-04-09 00:46:34 [24549] [INFO] Shutting down: Master
2014-04-09 00:46:34 [24583] [INFO] Starting gunicorn 18.0
2014-04-09 00:46:34 [24583] [DEBUG] Arbiter booted
2014-04-09 00:46:34 [24583] [INFO] Listening at: unix:/home/ec2-user/gunicorn.sock (24583)
2014-04-09 00:46:34 [24583] [INFO] Using worker: sync
2014-04-09 00:46:34 [24588] [INFO] Booting worker with pid: 24588
2014-04-09 00:46:34 [24589] [INFO] Booting worker with pid: 24589
2014-04-09 00:46:34 [24590] [INFO] Booting worker with pid: 24590
2014-04-09 00:46:37 [24589] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-09 00:46:42 [24590] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-09 04:46:43 [24589] [DEBUG] GET /
2014-04-09 04:46:44 [24590] [DEBUG] GET /
2014-04-09 04:46:45 [24589] [DEBUG] GET /
2014-04-09 04:46:46 [24590] [DEBUG] GET /
2014-04-09 04:46:46 [24589] [DEBUG] GET /
2014-04-09 04:46:47 [24590] [DEBUG] GET /
2014-04-09 04:46:48 [24589] [DEBUG] GET /
2014-04-09 04:46:49 [24590] [DEBUG] GET /
2014-04-09 04:46:50 [24589] [DEBUG] GET /
2014-04-09 00:46:54 [24588] [DEBUG] GET /
/usr/lib/python2.6/site-packages/setuptools-3.4.1-py2.6.egg/pkg_resources.py:1031: UserWarning: /home/ec2-user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2014-04-09 04:46:55 [24589] [DEBUG] GET /
2014-04-09 04:46:59 [24588] [DEBUG] GET /
